### ISSUE TITLE
Create documentation

### ISSUE THREAD

**Issue by PumpkinSeed** [zgendao/agora.space#5]
Create documentation for the project. It should have the details:
- What is the agora.space?
- How to use it?
- Additional information
- Contribution
  - How to setup the development environment if some want to develop it.
  
Add these changes to the README.md

**Comment by richardanyalai** [comment]
Related commits:
- [a518aea](https://github.com/zgendao/agora.space/commit/a518aea85821c8115d5d3da6f607c0a7bc5896d8)

**Comment by PumpkinSeed** [comment]
LGTM

@richardanyalai please mark this issue in the PR of this commit, and I considered it done
